#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check the status of round-robin multipath storage connections
# N.B. This script needs to be run with SUDO by the nagios user

vendor=$1

if [ ! -x /usr/sbin/multipath ] ; then
   echo "No multipath utility installed"
   exit 3
fi

if [ "$vendor" == "" ] ; then
   vendor=generic
fi

# the command to run to check the service
checkcommand="sudo /usr/sbin/multipath -ll"

if [ "$vendor" == "HP" ] ; then
   # HP arrays do not show missing paths as failed - they just get missing from the multipath output
   # In this case, we need to compare the number of primary and backup paths
   # Server internal SAS RAID cards do not show up in mutlipath for HP servers
   primary=`multipath -ll 2> /dev/null | egrep -c "status=active" | awk '{print $1}'`
   backup=`multipath -ll 2> /dev/null | egrep -c "status=enabled" | awk '{print $1}'`
 
   # The number of backup paths must be greater than or equal to the number of primary paths
   if [ $backup -lt $primary ] ; then
      echo "SAS multipath warning: $primary primary paths and $backup backup paths"
      exit 1
   else
      echo "SAS multipath OK: $primary primary and $backup backup paths"
      exit 0
   fi
fi

if [ `$checkcommand | grep -c faulty` -gt 0 ] ; then
   echo "SAS multipath warning"
   exit 1
fi

# Check for single-device multipath items (i.e. secondary path has failed before boot)
multipath -ll > /tmp/mpath.$$ 2>&1
onepathmap=0
for dev in `cat /tmp/mpath.$$ | awk '{print $3}' | grep "dm-"`
do
   paths=0
   for disk in `grep -A 10 $dev /tmp/mpath.$$ | sed 's?|??g' | awk '{print $3}' | egrep "^sd|dm-"`
   do
       if [ `echo $disk | grep -c sd` -ge 1 ] ; then
          paths=`expr $paths + 1`
       elif [ `echo $disk | grep -c "dm-"` -gt 1 ] ; then
          break
       fi
   done
   if [ $paths -lt 2 ] ; then
      onepathmap=`expr $onepathmap + 1`
   fi
done
rm -f /tmp/mpath.$$ > /dev/null
   
if [ `$checkcommand | fgrep \_ | egrep -v "prio|active|features"  | wc -l | awk '{print $1}'` -gt 0 ] ; then
   echo "SAS multipath warning: `$checkcommand | fgrep \_ | egrep -v "prio|active|features" | awk '{print $3,$5}'`"
   exit 1
elif [ $onepathmap -gt 0 ] ; then
   echo "$onepathmap multipath device(s) with only one path detected"
   exit 1
else
   echo "SAS multipath ok"
   exit 0
fi
