#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check the status of IBM P9 hardware
# N.B. actual status collection is performed by tool called by cron

checkdir=/var/spool/nagios/switch-status

totsw=0
totps=0
good=0
bad=0

for s in `ls -1 $checkdir | cut -d. -f1`
do
   totsw=`expr $totsw + 1`
   totps=`grep -c PS $checkdir/$s.out`
   good=`grep PS $checkdir/$s.out | grep -c OK`
   if [ $good -lt $totps ] ; then
      bad=`expr $bad + 1`
      switchname=`echo $switchname,$s`
   fi
done

swstring=`echo $switchname | sed 's?^,??g' | sed 's?,$??g'`

if [ $bad -gt 0 ] ; then
   echo "$bad switch(es) have failed PSU ($swstring)"
   exit 1
else
   echo "$totsw switches PSUs OK"
   exit 0
fi
   
