#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check for grid-engine jobs or queues in error state
. /etc/profile.d/alces-profiles.sh > /dev/null 2>&1

# Set the minimum number of job errors to warn us about
joberrorthreshold=10

# Set site variables (edit as necessary)
module -s load services/gridscheduler > /dev/null 2>&1 
export SGE_CELL="etc"
export SGE_CLUSTER_NAME="cluster"
export SGE_EXECD_PORT="6445"
export SGE_QMASTER_PORT="6444"
export SGE_ROOT="/opt/service/gridscheduler/"
PATH=$PATH:/opt/service/gridscheduler/bin/linux-x64/
qping=/opt/service/gridscheduler/bin/linux-x64/qping
qstat=qstat

# Check monitor application is present and executable
[[ -x `which $qstat` ]] || exit 3

qerrors=`$qstat -f | grep E | grep -- "linux-" | wc -l | awk '{print $1}'`
jerrors=`$qstat -u \* | grep E | grep -v PENDING | wc -l | awk '{print $1}'`

if [ $qerrors -gt 0 ] ; then
   echo "Detected $qerrors grid-engine queue error(s)"
   exit 1
elif [ $jerrors -gt $joberrorthreshold ] ; then
   echo "Number of grid-engine job errors ($jerrors) above warning threshold ($joberrorthreshold)"
   exit 1
elif [ $jerrors -gt 0 ] ; then
   echo "$jerrors grid-engine job error(s) detected - below alert threshold of $joberrorthreshold"
   exit 0
else
   echo "No grid-engine errors reported"
   exit 0
fi

# should never reach this point - exit with alert
exit 3


